plugins {
    id 'java'
    id 'application'
}

group = 'com.jogli.bootcamp.java8'
version = '1.0.0'
sourceCompatibility = '21'
targetCompatibility = '21'

repositories {
    mavenCentral()
}

application {
    mainClass = 'com.jogli.bootcamp.java8.Main'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
}

test {
    useJUnitPlatform()
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs = ['-Xlint:-options']
}

task runExamples(type: JavaExec) {
    group = 'application'
    description = 'Run all Java 8 examples'
    mainClass = 'com.jogli.bootcamp.java8.Main'
    classpath = sourceSets.main.runtimeClasspath
} 